openapi: 3.0.1
info:
  title: MyApp API
  description: API for interacting with MyApp to fetch item details.
  version: 'v1'
servers:
  - url: http://localhost:3000
paths:
  /api/items:
    get:
      summary: Get a list of items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Item 1"
                    description:
                      type: string
                      example: "This is item 1"

